# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DataUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DataWindow(object):
    def setupUi(self, DataWindow):
        DataWindow.setObjectName("DataWindow")
        DataWindow.resize(999, 841)
        self.centralwidget = QtWidgets.QWidget(DataWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_database = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_database.setObjectName("groupBox_database")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_database)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_personinfo = QtWidgets.QGroupBox(self.groupBox_database)
        self.groupBox_personinfo.setObjectName("groupBox_personinfo")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_personinfo)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableWidget_person_info = QtWidgets.QTableWidget(self.groupBox_personinfo)
        self.tableWidget_person_info.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidget_person_info.setShowGrid(True)
        self.tableWidget_person_info.setColumnCount(5)
        self.tableWidget_person_info.setObjectName("tableWidget_person_info")
        self.tableWidget_person_info.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_person_info.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_person_info.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_person_info.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_person_info.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_person_info.setHorizontalHeaderItem(4, item)
        self.gridLayout_2.addWidget(self.tableWidget_person_info, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_personinfo)
        self.verticalLayout_3.addWidget(self.groupBox_database)
        self.groupBox_checklog = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_checklog.setObjectName("groupBox_checklog")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_checklog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableWidget_report = QtWidgets.QTableWidget(self.groupBox_checklog)
        self.tableWidget_report.setColumnCount(5)
        self.tableWidget_report.setObjectName("tableWidget_report")
        self.tableWidget_report.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_report.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_report.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_report.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_report.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_report.setHorizontalHeaderItem(4, item)
        self.gridLayout_3.addWidget(self.tableWidget_report, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_checklog)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox_table = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_table.setObjectName("comboBox_table")
        self.comboBox_table.addItem("")
        self.comboBox_table.addItem("")
        self.comboBox_table.addItem("")
        self.comboBox_table.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_table)
        self.pushButton_create = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_create.setObjectName("pushButton_create")
        self.horizontalLayout.addWidget(self.pushButton_create)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comboBox_search = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_search.setObjectName("comboBox_search")
        self.comboBox_search.addItem("")
        self.comboBox_search.addItem("")
        self.comboBox_search.addItem("")
        self.comboBox_search.addItem("")
        self.comboBox_search.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_search)
        self.lineEdit_search = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.horizontalLayout_2.addWidget(self.lineEdit_search)
        self.pushButton_search = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_search.setObjectName("pushButton_search")
        self.horizontalLayout_2.addWidget(self.pushButton_search)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addWidget(self.groupBox)
        DataWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(DataWindow)
        QtCore.QMetaObject.connectSlotsByName(DataWindow)

    def retranslateUi(self, DataWindow):
        _translate = QtCore.QCoreApplication.translate
        DataWindow.setWindowTitle(_translate("DataWindow", "DataWindow"))
        self.groupBox_database.setTitle(_translate("DataWindow", "DataBase"))
        self.groupBox_personinfo.setTitle(_translate("DataWindow", "person_info"))
        self.tableWidget_person_info.setSortingEnabled(False)
        item = self.tableWidget_person_info.horizontalHeaderItem(0)
        item.setText(_translate("DataWindow", "PID"))
        item = self.tableWidget_person_info.horizontalHeaderItem(1)
        item.setText(_translate("DataWindow", "PName"))
        item = self.tableWidget_person_info.horizontalHeaderItem(2)
        item.setText(_translate("DataWindow", "PSex"))
        item = self.tableWidget_person_info.horizontalHeaderItem(3)
        item.setText(_translate("DataWindow", "PImgID"))
        item = self.tableWidget_person_info.horizontalHeaderItem(4)
        item.setText(_translate("DataWindow", "PPhone"))
        self.groupBox_checklog.setTitle(_translate("DataWindow", "Report"))
        item = self.tableWidget_report.horizontalHeaderItem(0)
        item.setText(_translate("DataWindow", "Name"))
        item = self.tableWidget_report.horizontalHeaderItem(1)
        item.setText(_translate("DataWindow", "Sex"))
        item = self.tableWidget_report.horizontalHeaderItem(2)
        item.setText(_translate("DataWindow", "ImgID"))
        item = self.tableWidget_report.horizontalHeaderItem(3)
        item.setText(_translate("DataWindow", "Phone"))
        item = self.tableWidget_report.horizontalHeaderItem(4)
        item.setText(_translate("DataWindow", "Time"))
        self.groupBox.setTitle(_translate("DataWindow", "Console"))
        self.label.setText(_translate("DataWindow", "Table"))
        self.comboBox_table.setItemText(0, _translate("DataWindow", "All"))
        self.comboBox_table.setItemText(1, _translate("DataWindow", "Day"))
        self.comboBox_table.setItemText(2, _translate("DataWindow", "Week"))
        self.comboBox_table.setItemText(3, _translate("DataWindow", "Month"))
        self.pushButton_create.setText(_translate("DataWindow", "Create"))
        self.label_2.setText(_translate("DataWindow", "Search"))
        self.comboBox_search.setItemText(0, _translate("DataWindow", "PID"))
        self.comboBox_search.setItemText(1, _translate("DataWindow", "PName"))
        self.comboBox_search.setItemText(2, _translate("DataWindow", "PSex"))
        self.comboBox_search.setItemText(3, _translate("DataWindow", "PImgID"))
        self.comboBox_search.setItemText(4, _translate("DataWindow", "PPhone"))
        self.pushButton_search.setText(_translate("DataWindow", "Search"))

