# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(847, 716)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.lineEdit_State = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_State.setReadOnly(True)
        self.lineEdit_State.setObjectName("lineEdit_State")
        self.horizontalLayout.addWidget(self.lineEdit_State)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.lineEdit_Time = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_Time.setReadOnly(True)
        self.lineEdit_Time.setObjectName("lineEdit_Time")
        self.horizontalLayout.addWidget(self.lineEdit_Time)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_Camera = QtWidgets.QLabel(self.groupBox)
        self.label_Camera.setObjectName("label_Camera")
        self.verticalLayout_4.addWidget(self.label_Camera)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_Camera = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_Camera.setObjectName("pushButton_Camera")
        self.horizontalLayout_5.addWidget(self.pushButton_Camera)
        self.pushButton_Start = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_Start.setCheckable(True)
        self.pushButton_Start.setObjectName("pushButton_Start")
        self.horizontalLayout_5.addWidget(self.pushButton_Start)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout_4.setStretch(0, 9)
        self.verticalLayout_4.setStretch(1, 1)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.lineEdit_PName = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_PName.setReadOnly(True)
        self.lineEdit_PName.setObjectName("lineEdit_PName")
        self.horizontalLayout_6.addWidget(self.lineEdit_PName)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.lineEdit_PSex = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_PSex.setReadOnly(True)
        self.lineEdit_PSex.setObjectName("lineEdit_PSex")
        self.horizontalLayout_7.addWidget(self.lineEdit_PSex)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_4)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit_PImgID = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_PImgID.setObjectName("lineEdit_PImgID")
        self.horizontalLayout_2.addWidget(self.lineEdit_PImgID)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.lineEdit_PPhone = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_PPhone.setText("")
        self.lineEdit_PPhone.setReadOnly(True)
        self.lineEdit_PPhone.setObjectName("lineEdit_PPhone")
        self.horizontalLayout_9.addWidget(self.lineEdit_PPhone)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_Edit = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_Edit.setCheckable(True)
        self.pushButton_Edit.setObjectName("pushButton_Edit")
        self.verticalLayout_3.addWidget(self.pushButton_Edit)
        self.pushButton_Search = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_Search.setObjectName("pushButton_Search")
        self.verticalLayout_3.addWidget(self.pushButton_Search)
        self.pushButton_InfoRE = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_InfoRE.setObjectName("pushButton_InfoRE")
        self.verticalLayout_3.addWidget(self.pushButton_InfoRE)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.horizontalLayout_4.addWidget(self.groupBox_4)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_Commit = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_Commit.setObjectName("pushButton_Commit")
        self.verticalLayout.addWidget(self.pushButton_Commit)
        self.pushButton_Delete = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_Delete.setObjectName("pushButton_Delete")
        self.verticalLayout.addWidget(self.pushButton_Delete)
        self.horizontalLayout_4.addWidget(self.groupBox_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_3.setTitle(_translate("MainWindow", "State"))
        self.label_3.setText(_translate("MainWindow", "Process"))
        self.label_4.setText(_translate("MainWindow", "NowTime"))
        self.groupBox.setTitle(_translate("MainWindow", "VedioRT"))
        self.label_Camera.setText(_translate("MainWindow", "Camera"))
        self.pushButton_Camera.setText(_translate("MainWindow", "Open"))
        self.pushButton_Start.setText(_translate("MainWindow", "Start"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Info"))
        self.label_5.setText(_translate("MainWindow", "PName "))
        self.label_6.setText(_translate("MainWindow", "PSex  "))
        self.label.setText(_translate("MainWindow", "PImgID"))
        self.label_8.setText(_translate("MainWindow", "PPhone"))
        self.pushButton_Edit.setText(_translate("MainWindow", "Edit"))
        self.pushButton_Search.setText(_translate("MainWindow", "Search..."))
        self.pushButton_InfoRE.setText(_translate("MainWindow", "Reset"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Console"))
        self.pushButton_Commit.setText(_translate("MainWindow", "Commit"))
        self.pushButton_Delete.setText(_translate("MainWindow", "Delete"))

